### ISSUE TITLE
storing an addclass when moving to different page

### ISSUE THREAD

**Issue by maitrishah25** [maitrishah25/cheesy_burritos#3]
Hi, I'm adding a class 'not-pad' to a table when I click on it. But once I navigate to a different page, the added class doesn't stay on the element. Similarly for when I click 'paid' on the receipt, I want to change the class of the table to paid as well...need the class to stick to the element when I navigate away from the page.

I think Andrew mentioned something about this with the data attribute.

Trying to get that to work.

Can we meet to talk through my flow and this above question?

**Comment by rapala61** [comment]
I totally get what you are trying to do, you want to somehow change the "state" of something after an action, and you want this "state" to persist so that navigating away and back to the page still reflects the change, this is a very common practice. 

You need to ask yourself, is this change being performed only by the browser, on the browser, or does my application know about it? If your application (server) doesn't know about it (through some change to the actual model), you wont be able to persist it in a practical way, this is because when you navigate away from the page you are tossing away all html code in the browser, together with the changes you made in the browser, and when it comes back, its drawn all over again based on your controller logic, views and the erb code in it.

I suggest you think about how to use conditional statements in your views, so that if certain criteria is met (maybe the ticket is paid), you can then use a different set of html, add classes, etc. in your view.

**Comment by maitrishah25** [comment]
Thanks! Will see if I can get it to work using conditionals in the models.

Had an issue with displaying all of the receipts. I set up a page to display all of the receipts as an accordion, showing the table number and party id, and when selected, drops down to show the entire receipt. From there, the server has the option to hit paid.

When I set this up, my error says that in my parties controller, it can't find a party with an id of editall and references a route for a different page. Trying to figure out what the issue is. Is this one of those things where the order of the routes in the controller page is making a difference?

I'm going to push my latest version so you can see my code.

**Comment by rapala61** [comment]
Great, the conditionals should go in the views not in the models. Create another issue for the last question and assign to Andrew , I will be out for a few hours for medical reasons.
